version: "3"
services:
  database:
    image: mariadb:latest
    restart: always
    ports:
      - "59487:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=Yue
      - MARIADB_USER=Yue
      - MARIADB_PASSWORD=test
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - TZ=Asia/Taipei
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
volumes:
  dbdata:
