on:
  push:
    tags:
      - 'v*.*.**'

jobs:
  test:
    uses: ./.github/workflows/unit-test.yml
  
  build-image-and-push:
    needs: test
    uses: ppodds/workflows/.github/workflows/build-and-push-image.yml@master
    with:
      image_name: yue
      registry: ${{ secrets.REGISTRY_URL }}
      image_tag: ${{ github.ref_name }}
      project_name: yue
    secrets:
      REGISTRY_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.HARBOR_TOKEN }}
