on:
  push:
    tags:
      - 'v*.*.**'

jobs:
  test:
    uses: ./.github/workflows/unit-test.yml
  
  build-image-and-push:
    needs: test
    uses: ppodds/workflows/.github/workflows/build-and-push-image.yml@master
    with:
      image_name: yue
      registry: https://harbor.ppodds.cc
      image_tag: ${{ github.ref_name }}
      project_name: yue
    secrets:
      REGISTRY_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.HARBOR_TOKEN }}
  
  trigger-deploy:
    needs: build-image-and-push
    uses: ppodds/workflows/.github/workflows/update-helm-chart.yml@master
    with:
      repo: ppodds/yue-helm
      app_version: ${{ github.ref_name }}
    secrets:
      TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
