on:
  push:
    tags:
      - 'v*.*.**'

jobs:
  test:
    uses: ./.github/workflows/unit-test.yml

  generate-image-tag:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: replace + with -
        id: get-tag
        run: |
          tag=${{ github.ref_name }}
          echo "tag=${tag//+/-}" >> $GITHUB_OUTPUT

  build-image-and-push:
    needs: generate-image-tag
    uses: ppodds/workflows/.github/workflows/build-and-push-image.yml@master
    with:
      image_name: yue
      registry: docker.io
      image_tag: ${{ needs.generate-image-tag.outputs.tag }}
      project_name: ppodds
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  
  trigger-deploy:
    needs: build-image-and-push
    uses: ppodds/workflows/.github/workflows/update-helm-chart.yml@master
    with:
      repo: ppodds/yue-helm
      app_version: ${{ github.ref_name }}
    secrets:
      TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
