name: Check yt-dlp version and update Dockerfile

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  get-latest-version:
    uses: ./.github/workflows/get-latest-ytdlp-version.yml
  get-current-version:
    uses: ./.github/workflows/get-current-ytdlp-version.yml
    with:
      branch: release
  check-need-update:
    runs-on: ubuntu-latest
    needs: [get-latest-version, get-current-version]
    outputs:
      need-update: ${{ steps.need-update.outputs.need_update }}
    steps:
      - name: Check if the latest version is newer than the current version
        id: need-update
        run: |
          latest=$(date -d ${{ needs.get-latest-version.outputs.latest-release-date }} +%s)
          current=$(date -d ${{ needs.get-current-version.outputs.current-release-date }} +%s)
          
          if [ $latest -gt $current ];
          then
              echo "need_update=true" >> $GITHUB_OUTPUT
          fi
  update:
    if: needs.check-need-update.outputs.need-update
    runs-on: ubuntu-latest
    needs: [get-latest-version, check-need-update]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Update the yt-dlp version in Dockerfile
        run: sed -E -i 's/https:\/\/github\.com\/yt-dlp\/yt-dlp\/releases\/download\/([0-9\.]+)\/yt-dlp/https:\/\/github\.com\/yt-dlp\/yt-dlp\/releases\/download\/${{ needs.get-latest-version.outputs.latest-release-tag }}\/yt-dlp/' Dockerfile
      - name: Get the current app version
        id: get-current-app-version
        run: |
          version=$(cat package.json | jq .version)
          version=${version//\"/}
          echo "version=$version" >> $GITHUB_OUTPUT
      - uses: EndBug/add-and-commit@v9
        with:
          add: Dockerfile
          default_author: github_actions
          message: 'chore: update yt-dlp to ${{ needs.get-latest-version.outputs.latest-release-tag }}'
          tag: 'v${{ steps.get-current-app-version.outputs.version }}+yt-dlp${{ needs.get-latest-version.outputs.latest-release-tag }}'
